/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SchoolRegister.forms;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author caule
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menEn = new javax.swing.JMenu();
        menEnStu = new javax.swing.JMenuItem();
        menEnCurse = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRel1 = new javax.swing.JMenuItem();
        menRel2 = new javax.swing.JMenuItem();
        menRel3 = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration");
        setPreferredSize(new java.awt.Dimension(1100, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(770, 530));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SchoolRegister/icons/studentsGeneralView1.png"))); // NOI18N

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setText("Date");

        menEn.setText("Enrollement");
        menEn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menEnStu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menEnStu.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menEnStu.setText("Student");
        menEnStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEnStuActionPerformed(evt);
            }
        });
        menEn.add(menEnStu);

        menEnCurse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menEnCurse.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menEnCurse.setText("Course");
        menEn.add(menEnCurse);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jMenuItem1.setText(" Registration");
        menEn.add(jMenuItem1);

        Menu.add(menEn);

        menRel.setText("Report");
        menRel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelActionPerformed(evt);
            }
        });

        menRel1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menRel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menRel1.setText("All students with a course");
        menRel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel1ActionPerformed(evt);
            }
        });
        menRel.add(menRel1);

        menRel2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        menRel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menRel2.setText("All courses for a student ");
        menRel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel2ActionPerformed(evt);
            }
        });
        menRel.add(menRel2);

        menRel3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menRel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menRel3.setText("All courses without students");
        menRel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel3ActionPerformed(evt);
            }
        });
        menRel.add(menRel3);

        Menu.add(menRel);

        menOpc.setText("Options");
        menOpc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menOpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menOpcSair.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        menOpcSair.setText("Close");
        menOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcSairActionPerformed(evt);
            }
        });
        menOpc.add(menOpcSair);

        Menu.add(menOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblDate))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblDate)
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1110, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menRel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel1ActionPerformed
        //Chamar o Filtros
        FiltroAForm filtroA = new FiltroAForm();
        filtroA.setVisible(true);
        desktop.add(filtroA);
        
        
    }//GEN-LAST:event_menRel1ActionPerformed

    private void menOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcSairActionPerformed
        // show dialog box with option yes or not
        int sair = JOptionPane.showConfirmDialog(null, "Do you want Logout?", "Attention", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menOpcSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Definir a data actual no lugar da lblData ao iniciar o form
        Date date = new Date();
        DateFormat dateformat = DateFormat.getDateInstance(DateFormat.LONG);
        //lblDate.setText(date.toString());
        lblDate.setText(dateformat.format(date));
    }//GEN-LAST:event_formWindowActivated

    private void menEnStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEnStuActionPerformed
        // Chamar o formulario estudantes
        StudentsForm students = new StudentsForm();
        students.setVisible(true);
        desktop.add(students);
    }//GEN-LAST:event_menEnStuActionPerformed

    private void menRel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel2ActionPerformed
        // Chamando 
        FiltroBForm filtrob= new FiltroBForm();
        filtrob.setVisible(true);
        desktop.add(filtrob);
    }//GEN-LAST:event_menRel2ActionPerformed

    private void menRel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel3ActionPerformed
        //Chamar o formC
        FiltroCForm filtroc=new FiltroCForm();
        filtroc.setVisible(true);
        desktop.add(filtroc);
    }//GEN-LAST:event_menRel3ActionPerformed

    private void menRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menRelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JMenu menEn;
    private javax.swing.JMenuItem menEnCurse;
    private javax.swing.JMenuItem menEnStu;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcSair;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRel1;
    private javax.swing.JMenuItem menRel2;
    private javax.swing.JMenuItem menRel3;
    // End of variables declaration//GEN-END:variables
}
